### PR TITLE
autopart root snapshot support

### PR DESCRIPTION
**Pull request by dwlehman**
Related to rhinstaller/pykickstart/pull/29

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me otherwise.

**Comment by mulkieran** [comment]
Other than comments above it looks good to me.

**Comment by mulkieran** [comment]
Ack.

**Comment by dwlehman** [comment]
I am dropping "Add installer support...", but will push the remaining four patches since they fix real problems.

**Pull request merged**
