### PR TITLE
Fix name of the keyword argument for luks_add_key

### PR DESCRIPTION
**Pull request by vpodzime**
It should be 'npass' not 'new_passphrase'.

### CODE REVIEW

**Comment by vpodzime** [comment]
I think this should also go to the f22-branch althought it is basically impossible to hit it from the installer (we don't allow adding multiple LUKS passphrases).

**Comment by vpodzime** [comment]
Added one more similar change to the commit that is needed.

**Comment by jsafrane** [comment]
It looks fine from OpenLMI point of view, our LUKS tests pass with the patch.

**Comment by bcl** [comment]
Looks good.

**Comment by vpodzime** [comment]
Rebased to the current master.

**Pull request merged**
