### PR TITLE
Fix invalid access to a name attribute on device name strings.

### PR DESCRIPTION
**Pull request by snowcrshd**
The findActiveDevicesOnActionDisks method returns a list with the names
(strings) of the active devices. There is not a 'name' attribute to be
accessed.

### CODE REVIEW

**Comment by mulkieran** [comment]
Bug is present in f21 also.

**Comment by dwlehman** [comment]
This was closed by accident when we did some branch management. rhel7-branch has moved, so you'll have to reset your local branch.

**Comment by lucastadeu** [comment]
@dwlehman could you please clarify? Has branch rhel7-branch been abandoned?
Ou should I simply do a rebase?

**Comment by dwlehman** [comment]
What was rhel7-branch prior to last Friday has been abandoned. The new rhel7-branch was created on the same day (Fri 29 May 2015) and is active. What you'll have to do, I think, is update your local rhel7-branch and then rebase your commit.

**Comment by lucastadeu** [comment]
I see; tried the rebase and got a few merge conflicts.

I'll look into it, though.

**Comment by lucastadeu** [comment]
Branch updated.

**Comment by dwlehman** [comment]
It occurs to me only now that there are stringent restrictions on what can be pushed to rhel7-branch. To get this pushed there we will need a bugzilla bug report, which will need to be approved for inclusion in a specific release of RHEL-7.

If this is an issue on master, however, we would be quite happy to apply the fix there.

**Comment by mulkieran** [comment]
This is fixed on master.

**Comment by mopsfelder** [comment]
@dwlehman how do we open a bugzilla for this to be fixed in RHEL 7?

**Comment by dwlehman** [comment]
@mopsfelder sorry for the massive delay in answering -- I totally missed your question.

To get this onto rhel7-branch you would need to make a request through your Red Hat support contact. If you don't have one, you could just open a bug at bugzilla.redhat.com.

**Comment by mopsfelder** [comment]
@dwlehman Thank you for responding (even though almost 2 years later).

This issue is not in our radar anymore, i.e. we will not chase it down.  Feel free to close or apply it.

**Pull request closed without merging**
