### PR TITLE
A simple script for multi-merges we now do

### PR DESCRIPTION
**Pull request by vpodzime**
Merging PRs into multiple branches is a tedious and error prone work. In order
to make our lives easier, here comes a simple script doing the multi-merge in a
way we want it to happen.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Looks good to me.

**Comment by dwlehman** [comment]
This makes me a bit nervous about people merging commits from their local branches unintentionally.

**Comment by vpodzime** [comment]
> This makes me a bit nervous about people merging commits from their local branches unintentionally.

Do you think it should merge ``$origin/$src``?

**Comment by dwlehman** [comment]
I guess that would alleviate my concern.

**Comment by vpodzime** [comment]
Done.

**Comment by vpodzime** [comment]
That didn't really work and the merge commits looked weird. So I added this check instead:
```
# checkout the $origin/$src branch to check if it exists and thus prevent
# merging local branches
git checkout $origin/$src
```
In combination with ``set -e`` this makes sure that it's not just some weird local branch. And ``git rebase $origin/$src`` below that makes sure the to-be-merged branch is up to date.

**Pull request merged**
