### PR TITLE
Workaround for chrooted mountpoints  (#1217578)

### PR DESCRIPTION
**Pull request by vojtechtrefny**
This solution is definitely not the ideal one but at least it fixes the problem with failing atomic builds. It is neccessary to come up with a better solution for all nodev devices and its mountpoints.

-----
These are currently failing because of mounts cache. The problem is mostly with chrooted mounts and bind mounts of 'nodev' devices. This solution is definitely not ideal one but at least it fixes the problem with failing atomic builds. It is neccessaty to come up with a better solution for all nodev devices and its mountpoints.

### CODE REVIEW

**Comment by mulkieran** [comment]
Is it really impossible to handle this problem in mountsCache itself?

**Comment by vpodzime** [comment]
> Is it really impossible to handle this problem in mountsCache itself?

It's not entirely easy and no way we could come up with looked safe enough to be applied fast. As @vojtechtrefny mentioned above *"This solution is definitely not the ideal one but at least it fixes the problem with failing atomic builds."* which we should do ASAP.

**Comment by vojtechtrefny** [comment]
Updated version based on @vpodzime comments.

@mulkieran as @vpodzime already mentioned, this is only temporary workaround. I tried to fix the mountsCache to be able to work with nodev filesystems and bind mounts but there is just too many problems and it will need some time and more testing.

**Comment by mulkieran** [comment]
ok, so long as we all explicitly agree that it's a _temporary_ fix that will be reverted soon, and it does fix the atomic builds, I'm fine w/ it.

**Comment by vojtechtrefny** [comment]
Pushed.

**Pull request closed without merging**
