### PR TITLE
Master hawkey

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by mulkieran** [comment]
Had to update this slightly, catching an IOError when loading the system repo.

**Comment by vpodzime** [comment]
> Had to update this slightly, catching an IOError when loading the system repo.

It seems almost like a bug in *hawkey* that they just pass the ``IOError`` further from their calls. In which cases is this exception raised? They should probably "wrap it" in their own exception class. And we should at least add a comment describing the weird case when it gets raised. With that added this still looks good to me.

**Comment by mulkieran** [comment]
Yes, it is a bit weird. Comment added, bz posted.

**Comment by vpodzime** [comment]
Thanks!

**Pull request merged**
