### PR TITLE
Add make-sphinx-docs helper script

### PR DESCRIPTION
**Pull request by bcl**

### CODE REVIEW

**Comment by jkonecny12** [comment]
Thank you for this script. It will be helpful.
Looks good to me.

**Comment by dwlehman** [comment]
Is this to help when we move away from readthedocs?

**Comment by bcl** [comment]
> Is this to help when we move away from readthedocs?

Yes, or to help build them locally as a preview.

**Comment by vpodzime** [comment]
Looks good to me too.

**Comment by bcl** [comment]
> Looks good to me too.

We're going to just let this one sit for now.

**Pull request closed without merging**
