### PR TITLE
Fixes for cached LV VG space used

### PR DESCRIPTION
**Pull request by vpodzime**
These fixes some inconsistencies and problems @vojtechtrefny found when working on LVM cache and LVM RAID support in *blivet-gui*.

### CODE REVIEW

**Comment by vpodzime** [comment]
This needs some more refinements as the tests fail right now.

**Comment by dwlehman** [comment]
That's okay with me, but it will have to be addressed before we pull this into a release.

**Comment by vpodzime** [comment]
> That's okay with me, but it will have to be addressed before we pull this into a release.

Fair enough. However, I'm not sure how much time I want to spend on it if we may end up removing/avoiding the padding entirely as suggested by the LVM team recently.

**Comment by vpodzime** [comment]
I need to take a second look on this. In any case, these changes are going to -devel branches now so I'm closing this PR.

**Pull request closed without merging**
