### PR TITLE
Fix removing PVs after removing VG (#1358067)

### PR DESCRIPTION
**Pull request by vojtechtrefny**
Set `vgName` in lvmpv format to `None` when removing the vg, so we can remove the pv too.

### CODE REVIEW

**Comment by dwlehman** [comment]
I'm not sure that "cannot replace active format" error makes any sense to raise in any case.

**Comment by vojtechtrefny** [comment]
Added a new patch to ignore pylint errors. I think these are some bugs in pylint, because it just started failing without changes.

**Comment by vojtechtrefny** [comment]
@dwlehman The exception message is a little misleading, "remove" would be probably better than "replace" because we're trying to remove the PV not "replace" it.

**Comment by dwlehman** [comment]
It would be a real error to remove an active format, but we're only changing the model -- not actually removing anything. This was a paranoid check from when I first wrote blivet and didn't know exactly which conditions were going to be relevant. I tend to think we can remove that check/raise completely.

**Comment by vojtechtrefny** [comment]
I think it isn't that paranoid. At least in this case -- we probably don't want to remove a PV that is part of a VG.

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by dwlehman** [comment]
Although I still don't think the exception raised makes sense, what you are doing does look correct.

**Pull request merged**
