### PR TITLE
Ignore and clean files generated by Sphinx

### PR DESCRIPTION
**Pull request by atodorov**
Just cleaning up a bit.

### CODE REVIEW

**Comment by mulkieran** [comment]
AFAICT, almost all the .rst files are ignored. Might be better to ignore all .rst files and use
! to leave out the ones that should not be ignored, like intro.rst and index.rst in .gitignore file.

Might be better to autogenerate most of the module names that are deleted in Makefile, too.

**Comment by atodorov** [comment]
.gitignore should look better now but I have no idea how would you like to autogenerate the module names in the Makefile. Any suggestions ?

**Comment by mulkieran** [comment]
using wildcards and things. It is probably not worth the trouble at this time. I'll ack it as is...

**Comment by atodorov** [comment]
With #144 in the works I guess this can be closed. Reopen if you think otherwise.

**Pull request closed without merging**
