### PR TITLE
Fix extended resize

### PR DESCRIPTION
**Pull request by vojtechtrefny**
Fix resizing of extended partitions:
1) Report minSize as size of extended partition - size of free space at the end of it. (Blivet now reports 0 B.) Fixes #1254875
2) Allow resizing of non-leaf partitions.

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me since the newly added method looks like it's ``StorageDevice._preDestroy()`` merged with ``PartitionDevice._preDestroy()`` without the ``isLeaf()`` check. Size calculations look good to me.

**Comment by vojtechtrefny** [comment]
New version based on @dwlehman comments:
- aligned minSize -- fixed
- minSize for empty extended partition -- 1 KiB (2 sectors) is what system reports as size for extended partition; not sure about the grainSize -- is it possible to be smaller than that?
- resizing of non-leaf partitions -- fixed to work only on extended partitions

**Comment by vpodzime** [comment]
> resizing of non-leaf partitions -- fixed to work only on extended partitions

Is it even possible there would be a non-leaf partition that is not extended?

This still looks good to me.

**Comment by vojtechtrefny** [comment]
resizing of non-leaf partitions -- fixed to work only on extended partitions

    Is it even possible there would be a non-leaf partition that is not extended?

Yes, every partition with children -- PVs, mdmembers, encrypted partitions...

**Comment by dwlehman** [comment]
This looks good to me, except that it really needs unit tests. This is a great example of the kind of code that should have unit tests covering it to ensure people don't break it in the future without realizing it.

**Comment by vojtechtrefny** [comment]
Test added.

**Comment by vpodzime** [comment]
Nice! The test looks good to me.

**Comment by dwlehman** [comment]
Thanks for adding the test -- it looks good.

**Comment by vojtechtrefny** [comment]
Pushed.

**Pull request closed without merging**
