### PR TITLE
Blacklisted attrs should be unwrapped, not omitted.

### PR DESCRIPTION
**Pull request by dwlehman**
Thanks for pointing out the problem, @vojtechtrefny.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Looks good to me.

**Comment by vpodzime** [comment]
Same here.

**Comment by jkonecny12** [comment]
Could you please rename ``wrapped`` list to something else because now it has wrapped and blacklisted items too.

**Comment by dwlehman** [comment]
It has always contained both wrapped and unwrapped attributes. I will try to think of a better name for the dict.

**Comment by jkonecny12** [comment]
Looks much better to me now. Thank you.

**Pull request merged**
