### PR TITLE
CONTRIBUTING update

### PR DESCRIPTION
**Pull request by vpodzime**
Two minor updates to our CONTRIBUTING file.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Looks good to me.

**Comment by dwlehman** [comment]
Hmm, I guess this has become inaccurate since we've changed the branching policy. Maybe just push the one that removes the python3-check bit?

**Comment by vpodzime** [comment]
> Hmm, I guess this has become inaccurate since we've changed the branching policy. Maybe just push the one that removes the python3-check bit?

Yeah, that's the only bit that makes sense. I think this can go just to *master*. Or do you think it should go to the *-devel* branches too?

**Comment by vpodzime** [comment]
Obsoleted by PR #362

**Pull request closed without merging**
