### PR TITLE
LVM cache creation

### PR DESCRIPTION
**Pull request by vpodzime**
Commits that add support for creation of cached LVs plus two minor changes that make things a bit nicer. Please note that I'm intentionally leaving the changes in the last commit as a standalone commit as it needs some attention.

### CODE REVIEW

**Comment by vpodzime** [comment]
Fixed a pylint warning.

**Comment by vpodzime** [comment]
New version using PV devices instead of just their names.

**Comment by vojtechtrefny** [comment]
Looks good to me.

**Comment by dwlehman** [comment]
Some unit tests to go along with this would be really nice.

**Comment by vpodzime** [comment]
> Some unit tests to go along with this would be really nice.

I'll definitely implement some once this gets merged and has some "final" state. I first wanted to catch up with rhel7-branch and its support for LVM cache. Now I can work on both unit tests and kickstart tests for anaconda.

**Pull request merged**
