### PR TITLE
Adapt to the old-new storaged API paths

### PR DESCRIPTION
**Pull request by vpodzime**
storaged now provides the API compatible with UDisks2.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Looks good to me.

**Comment by dwlehman** [comment]
Are they removing the storaged paths?

**Comment by dwlehman** [comment]
I think it would be quite a lot of effort, if not impossible, to provide two distinct namespaces from the same dbus service. Presumably they're removing the storaged ones.

**Comment by vpodzime** [comment]
> I think it would be quite a lot of effort, if not impossible, to provide two distinct namespaces from the same dbus service. Presumably they're removing the storaged ones.

Exactly.

**Comment by vpodzime** [comment]
I just want to wait with this for the actual change to happen in Rawhide (should be any time soon).

**Pull request merged**
