### PR TITLE
F22 1208536

### PR DESCRIPTION
**Pull request by mulkieran**
Also for master.

### CODE REVIEW

**Comment by vpodzime** [comment]
Other than the two neatpicks above this looks good to me. And I keep my fingers crossed in a hope this is going to be the last piece in the *F22 FW RAID Saga*

**Comment by mulkieran** [comment]
The last two or three are new, but the first two are the original.

**Comment by AdamWill** [comment]
FWIW I've tested this, with an updates.img containing these changes I can complete install to a RAID-0 set and boot to the installed system.

**Comment by vpodzime** [comment]
This all look good to me.

**Pull request merged**
