### PR TITLE
Exclude isodir from valid disks

### PR DESCRIPTION
**Pull request by jkonecny12**
When dracut downloads stage2 from the repository on the iso *(inst.repo=hd:...)* this iso file will mount to ``isodir`` so if ``isodir`` was mounted we can't use the source device in a partitioning.

I don't know if this is the correct way to fix it so I would be glad if @vpodzime or @dwlehman could look on it and give me some feedback.

~~*Will go to master too.*~~

### CODE REVIEW

**Comment by vpodzime** [comment]
Honestly, I'd rather see the whole block you are extending to go away from blivet. I think we could just extend it for f23-branch, but on master, we should come up with some cleaner solution (in particular not have anaconda's weird paths in blivet's sources).

**Comment by jkonecny12** [comment]
I don't like it too that's why I asked if this is correct way to do this.
I think cleaner solution for this will be to give it from anaconda to blivet somehow but I'm not enough familiar with blivet now to know how to do it.

**Comment by bcl** [comment]
I agree, what I'd try to do is make some way for anaconda to pass in a list of paths for blivet to ignore and make the blivet code more general, just checking a list.

**Comment by jkonecny12** [comment]
Is possible solution when the protected is set for device then it automatically set it to the parent disk? 

Or better case create there counter and add +1 for every protected child device and -1 for every protected = false call. And return ``true`` ``if >=0`` for disk device.

**Comment by bcl** [comment]
I don't think there's much wrong with the current code, other than hard-coding paths. It already sets the parent's protected attr.

**Comment by jkonecny12** [comment]
Yeah but when you want to remove this hard-coded paths (and we don't want them, because this should be in anaconda not blivet) we need to find some other way.
I already consulted this with @vpodzime and I think we have one. 

Question is, do we want this or the cleaner version to f23-branch in other words could I push this to f23 and close it @vpodzime @bcl ?

**Comment by vpodzime** [comment]
> Question is, do we want this or the cleaner version to f23-branch in other words could I push this to f23 and close it @vpodzime @bcl ?

Works for me.

**Comment by bcl** [comment]
I'm fine with it for F23.

**Comment by jkonecny12** [comment]
Pushed. Thank you for help.

**Pull request closed without merging**
