### PR TITLE
Add a public API specification

### PR DESCRIPTION
**Pull request by dwlehman**
Where a class is listed that means instantiating that class is supported. Where is it not, we are specifying the public methods and attributes. There are some issues with undocumented members and singletons, but they are minor.

### CODE REVIEW

**Comment by vpodzime** [comment]
So if for example ``~blivet.devices.lvm.LVMLogicalVolumeDevice`` is listed, it means that all its methods, attributes and properties are part of the API?

**Comment by dwlehman** [comment]
It means the constructor, any listed methods/attributes, and all methods/attributes listed in superclasses are public.

**Comment by dwlehman** [comment]
Would it be clearer (if a bit verbose) to explicitly list everything for each class?

**Comment by vpodzime** [comment]
Well, what if I want one or two methods/attributes not being part of the API?

**Comment by dwlehman** [comment]
Then you don't list them in the API spec.

**Comment by dwlehman** [comment]
By "listed" I mean "listed in the API spec".

**Comment by vpodzime** [comment]
> Then you don't list them in the API spec.

Sure, do I need to list all the other methods/attributes then?

**Comment by dwlehman** [comment]
Yes, and this makes it clear that I should convert it so that every method/attribute is explicitly listed directly in the list for that class instead of expecting users to check the superclass' list.

**Comment by dwlehman** [comment]
New version has several changes:
- the public API specification is more explicit
- the TOC now only shows top-level items: Introduction, Public API, Testing, &c
- the existing singleton modules were cleaned up a bit:
  - instance and class names don't match
  - class names are public so they get documented
- direct access to full module docs from the streamlined TOC
  - old: blivet->blivet package
  - new: blivet package

@vpodzime please check to see if I missed anything in the new LVM classes.

**Comment by dwlehman** [comment]
Isn't `map_name` equal to `name` for `DMDevice` (including lvs)?

What about `is_thin_lv`, `is_thin_pool`, `is_snapshot_lv`?

**Comment by dwlehman** [comment]
Latest version includes the following changes:
- fixed a typo in the singleton cleanup patch
- added more to lvm device API
- drop sphinx mocking entirely (it wasn't working)

**Comment by dwlehman** [comment]
You can see a preview of the docs [here](https://dlehman.fedorapeople.org/docs/).

**Comment by vpodzime** [comment]
> Isn't map_name equal to name for DMDevice (including lvs)?
It is, right now, but will users of the API know? And is it going to stay like that in the future? I imagine us using e.g. ``vg_name/lv_name`` for LV name.

> 
> What about is_thin_lv, is_thin_pool, is_snapshot_lv?
Good catch! These too, plus ``is_internal_lv``.

**Comment by vpodzime** [comment]
Looks good to me otherwise.

**Pull request merged**
