### PR TITLE
Fix an overly inclusive regex in DeviceTree.resolveDevice.

### LINKED ISSUE #152: resolveDevice fails on systems with > 15 disks due to bad regex
In my Anaconda kickstart config, I'm specifying partition information for 16 disks, sda-sdp. When kickstart calls out to blivet/devicetree.py to look up device mappings for each of the drives, it dies and creates a traceback when resolveDevice(sdp) is being processed.

There's a regex on line 2548 that appears to be the root cause, because the device name contains 'p' it matches this regex and causes blivet to do the wrong thing:

https://github.com/rhinstaller/blivet/blob/rhel7.1-branch/blivet/devicetree.py#L2548 :
```python
  elif re.match(r'(0x)?[A-Za-z0-9]{2}(p\d+)?$', devspec):
```
I'm not exactly sure what this regex is intended to match, (I'm assuming something like "disk1p1") so anchoring it at the beginning may/may not be a trivial fix.

A simple example:
```python
>>> import re
>>> if re.match(r'(0x)?[A-Za-z0-9]{2}(p\d+)?$', 'sdp1'):
...   print "matched"
...
matched
>>> if re.match(r'(0x)?[A-Za-z0-9]{2}(p\d+)?$', 'sdq1'):
...   print "matched"
...
>>>
```

A copy of the Anaconda config+traceback error, storage.log illustrating the problem, are in this gist:
https://gist.github.com/bwann/b8286b72613c03b98ee7  This is from Anaconda 19 with CentOS 7.1, and the regex is the same even in trunk.

### PR DESCRIPTION
**Pull request by dwlehman**
This prevented proper resolution of some partition names.

Fixes #152

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me. I just don't quite remember what was our decision about using the #NUMBER in commit messages for GH issues.

**Comment by bcl** [comment]
Needs a test though ;)

**Comment by dwlehman** [comment]
Yeah, writing tests for DeviceTree.resolveDevice is something I keep putting off doing.

**Comment by dwlehman** [comment]
New version has tests!

**Comment by bcl** [comment]
Perfect!

**Pull request merged**
