### PR TITLE
Increase the default size of /boot to 1 GB.

### PR DESCRIPTION
**Pull request by clumens**
This provides more space to store yet more kernels.

Resolves: rhbz#1270883

### CODE REVIEW

**Comment by dwlehman** [comment]
You'll want to open another pull request against 2.0-devel if this is also destined for rawhide/f25.

**Comment by clumens** [comment]
Yeah, definitely.  I think we should talk about it for Fedora first, though.  They may have different plans there.

**Comment by dwlehman** [comment]
I want to note that doing this on rhel7-branch without having decided on a course of action for newer branches introduces an opportunity for a regression if there is no follow-up.

**Comment by clumens** [comment]
Yeah, good point.  I don't really want us to have to maintain this off on the side in rhel-whatever branches for all time, but I also don't really want to get into this in fedora-devel.  I could at least start something on anaconda-devel-list, though.

**Pull request merged**
