### PR TITLE
Makefile rc-release target and associated support

### PR DESCRIPTION
**Pull request by bcl**
This allows us to make scratch rpms with a version-release that allows it to be used before the next official release. Useful for nightly testing and such.

### CODE REVIEW

**Comment by dwlehman** [comment]
My brain is too fried to conduct a thorough review, but this looks good in principle.

**Comment by vpodzime** [comment]
Other than the minor commens above this looks good to me.

**Comment by clumens** [comment]
This all looks solid to me, though now I am starting to wonder:  Do we want to find a way to share makebumpver and Makefile targets?

**Comment by mulkieran** [comment]
Yes, we would really like to share makebumpver. Just so you know, the version in different packages have diverged _a lot_, since they migrated. So it would be kind of challenging.

**Comment by bcl** [comment]
I don't think so. They're similar, but still different enough that any effort to make them common would just add a 3rd place to edit things.

**Comment by clumens** [comment]
Perhaps pocketlint (which is right now just a place where I'm moving all our pylint stuff to be shared) could also function as a place to store makebumpver?  In that case, do I want to rename it to something more generic?  Though that is a very good name.  Sharing Makefile stuff - okay, maybe that's too hard.

**Pull request closed without merging**
