### PR TITLE
Mount efivarfs during os installation (#1260799)

### PR DESCRIPTION
**Pull request by bcl**
Tools running inside the chroot need access to /sys/firmware/efi/efivars
if it exists on the host. eg. efibootmgr

### CODE REVIEW

**Comment by AdamWill** [comment]
Sorry, there's an error in this:

    Traceback (most recent call first):
      File "/tmp/updates/blivet/formats/__init__.py", line 327, in _setDevice
        raise ValueError(error_msg)
      File "/tmp/updates/blivet/formats/__init__.py", line 334, in <lambda>
        lambda f,d: f._setDevice(d),
      File "/tmp/updates/blivet/formats/__init__.py", line 190, in __init__
        self.device = kwargs.get("device")
      File "/tmp/updates/blivet/formats/__init__.py", line 85, in getFormat
        fmt = fmt_class(*args, **kwargs)
      File "/tmp/updates/blivet/osinstall.py", line 320, in efivars
        self._efivars = NoDevice(fmt=getFormat("efivarfs", device="efivarfs", mountpoint="/sys/firmware/efi/efivars"))
      File "/tmp/updates/blivet/osinstall.py", line 564, in mountFilesystems
        devices.append(self.efivars)
      File "/tmp/updates/blivet/blivet.py", line 1409, in mountFilesystems
        readOnly=readOnly, skipRoot=skipRoot)
      File "/tmp/updates/blivet/osinstall.py", line 1082, in turnOnFilesystems
        storage.mountFilesystems()
      File "/usr/lib64/python3.4/site-packages/pyanaconda/install.py", line 195, in doInstall
        turnOnFilesystems(storage, mountOnly=flags.flags.dirInstall, callbacks=callbacks_reg)
      File "/usr/lib64/python3.4/threading.py", line 868, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 253, in run
        threading.Thread.run(self, *args, **kwargs)
    ValueError: device must be a fully qualified path

**Comment by AdamWill** [comment]
I *think* what's needed here (the reason all those other `NoDevice` properties work fine) is a class in `formats/fs.py` - if there isn't one, `getFormat` falls back on `DeviceFormat`, and it's `DeviceFormat._deviceCheck()` that's giving us the 'must be a fully qualified path' error.

**Comment by AdamWill** [comment]
If I add this:

    --- a/blivet/formats/fs.py
    +++ b/blivet/formats/fs.py
    @@ -1297,3 +1297,9 @@ class USBFS(NoDevFS):
         _type = "usbfs"
     
     register_device_format(USBFS)
    +
    +
    +class EFIVarFS(NoDevFS):
    +    _type = "efivarfs"
    +
    +register_device_format(EFIVarFS)

to @bcl 's patch then the install runs, and I can see that selinuxfs is mounted twice now. However it's mounted with different options in the install root:

    efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
    efivarfs on /mnt/sysimage/sys/firmware/efi/efivars type efivarfs (rw,relatime)

not sure if we need to tweak the EFIVarFS class to fix that. It does seem to *work*, though: `efibootmgr` calls succeed again and there's no error, and I can run `efibootmgr` manually from after doing a `chroot` also.

**Comment by jwboyer** [comment]
> to @bcl 's patch then the install runs, and I can see that selinuxfs is mounted twice now.

I think you meant efivarfs here?  Just checking...

**Comment by AdamWill** [comment]
yes. :) edited

**Comment by bcl** [comment]
pushed.

**Pull request closed without merging**
