### PR TITLE
Eliminate mountpoint symlinks when looking for mounted device

### PR DESCRIPTION
**Pull request by vojtechtrefny**
#479 for 2.0-devel and master

### CODE REVIEW

**Comment by vpodzime** [comment]
Jenkins, please test this.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
Looks good @vpodzime

**Comment by jkonecny12** [comment]
It was @vpodzime, I'm eyewitness to that :laughing:

**Pull request merged**
