### PR TITLE
RFC: Add a file with release notes

### PR DESCRIPTION
**Pull request by vpodzime**
These are more high-level notes about changes done in the releases (at least
major). Useful for people outside of the team, but also for us to easily find
out when and in to what extent something was added.

I believe everybody know what the difference between changelog and release notes is.

Also, obviously, this should be merged after the LVM RAID PR #286 gets merged and then amended with more content related to other big changes.

### CODE REVIEW

**Comment by dwlehman** [comment]
This is a good idea. I wonder if we can reference files in the tree from the wiki so people can find the release notes in either place without us having to maintain two copies.

**Comment by vpodzime** [comment]
> This is a good idea. I wonder if we can reference files in the tree from the wiki so people can find the release notes in either place without us having to maintain two copies.

You mean the wiki here on GitHub?

**Comment by dwlehman** [comment]
Yes.

**Comment by vpodzime** [comment]
We can definitely add a link to the file in the tree. Something like:

The release notes can be found [here] (https://github.com/vpodzime/blivet/blob/master-release_notes/release_notes.rst)

GitHub takes care of the nice rendering.

**Comment by vpodzime** [comment]
Or it should be possible to have the wiki as a git submodule in the sources (http://brendancleary.com/2013/03/08/including-a-github-wiki-in-a-repository-as-a-submodule/), but I think it's not worth it.

**Comment by vojtechtrefny** [comment]
It should be possible to link it (or even directly display/embed) the release notes from our website (Drupal has some support for RST rendering).

**Pull request merged**
