### PR TITLE
Add unit tests for the LVM cache support

### PR DESCRIPTION
**Pull request by vpodzime**
So that we can catch possible regressions easily in the future.

### CODE REVIEW

**Comment by dwlehman** [comment]
Please also add assert statements to some of the other lvm tests to ensure they correctly report themselves as not being cached -- maybe device_properties_test is a good place for that.

**Comment by vpodzime** [comment]
That's a good point, will do.

**Comment by vpodzime** [comment]
Added one more check to the LVM cache support unit test (``vgSpaceUsed``), one fix and tests that make sure both cached and not-cached LVs report expected values of required properties.

**Comment by vojtechtrefny** [comment]
Looks good to me.

**Pull request merged**
