### PR TITLE
Master fixups

### PR DESCRIPTION
**Pull request by bcl**

### CODE REVIEW

**Comment by vpodzime** [comment]
My version of the "Make sure the file exists..." patch is sitting on the anaconda-patches list since Friday. :) The "Drop self.status from..." looks good to me.

**Comment by bcl** [comment]
> My version of the "Make sure the file exists..." patch is sitting on the anaconda-patches list since Friday.

Could have sworn I ack'd that or someone else did. I do remember reading it. Consider this an ACK since I don't have that email anymore.

> This should probably return mountpoint != self.systemMountpoint or whatever that would look like with all the recent changes. The idea is to return False if you should not proceed with the actual mount command.

Ok.

**Comment by dwlehman** [comment]
Setting ack under the assumption that the file size patch is dropped.

**Comment by bcl** [comment]
Pushed just that 1 patch.

**Pull request closed without merging**
