### PR TITLE
Small tests/ fixes

### PR DESCRIPTION
**Pull request by atodorov**
Following up with a PR after the IRC discussion.

### CODE REVIEW

**Comment by mulkieran** [comment]
Except please extend commit message to mention that tests/lib was previously used for pylint and now pocketlint is used instead.

**Comment by atodorov** [comment]
@mulkieran - I've just noticed a tests/testenv.sh file which also appears to be obsolete. Should I go ahead and remove it too ?

**Comment by mulkieran** [comment]
Yes! Thanks for noticing.

**Comment by mulkieran** [comment]
Superseded by #143.

**Pull request closed without merging**
