### PR TITLE
Blivet 2.0 builds

### PR DESCRIPTION
**Pull request by vojtechtrefny**
Two changes for blivet 2.0 builds.

https://copr.fedoraproject.org/coprs/vtrefny/blivet-2.0/

### CODE REVIEW

**Comment by jkonecny12** [comment]
Seems good to me.

**Comment by vpodzime** [comment]
Looks good to me too.

**Comment by dwlehman** [comment]
Looks good.

**Comment by vojtechtrefny** [comment]
Pushed.

**Pull request closed without merging**
